# Generated by Django 5.2.6 on 2025-09-12 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cammouflagebackend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadimagemodel",
            name="caption",
        ),
    ]
